/**
 *? Generated by meta_gen filter
 *! Edits will be discrded!
 */

/**
 * Contains meta information about the pack, such as version and git info.
 * This information is generated at build time and can be used in the code to display version info or for debugging purposes.
 */
const Meta = {
  manifest: {
    bp: {
      version: [5, 1, 0],
      min_engine_version: [1, 20, 80],
    },
    rp: {
      version: [5, 1, 0],
      min_engine_version: [1, 21, 80],
    },
  },
  github: {
    commit: "5d2ecc3ee93584bce8c7c0a63cced82b481642b3",
    tag: "v5.1.0",
  },
} as const;

export default Meta;
