
scoreboard objectives remove guib
scoreboard objectives remove traitCd
scoreboard objectives remove trait
scoreboard objectives remove perk
scoreboard objectives remove ctrl

scoreboard objectives remove webbing
scoreboard objectives remove claustrophobia
scoreboard objectives remove shulkInvId
scoreboard objectives remove phantomized
scoreboard objectives remove slimesize
scoreboard objectives remove inchlingspeed
scoreboard objectives remove stinger
scoreboard objectives remove starstress
scoreboard objectives remove starleap
scoreboard objectives remove starprojectile
scoreboard objectives remove piglindef
scoreboard objectives remove elvenlink
scoreboard objectives remove darkenergy

scoreboard objectives remove resource_bar1id
scoreboard objectives remove resource_bar1from
scoreboard objectives remove resource_bar1to
scoreboard objectives remove resource_bar1duration

scoreboard objectives remove resource_bar2id
scoreboard objectives remove resource_bar2from
scoreboard objectives remove resource_bar2to
scoreboard objectives remove resource_bar2duration

scoreboard objectives remove resource_bar3id
scoreboard objectives remove resource_bar3from
scoreboard objectives remove resource_bar3to
scoreboard objectives remove resource_bar3duration

scoreboard objectives remove resource_barAid
scoreboard objectives remove resource_barAfrom
scoreboard objectives remove resource_barAto
scoreboard objectives remove resource_barAduration

scoreboard objectives remove resource_barBid
scoreboard objectives remove resource_barBfrom
scoreboard objectives remove resource_barBto
scoreboard objectives remove resource_barBduration

scoreboard objectives remove resource_barCid
scoreboard objectives remove resource_barCfrom
scoreboard objectives remove resource_barCto
scoreboard objectives remove resource_barCduration
